SELECT TOP (1000) [ID]
      ,[Title]
      ,[Description]
      ,[ProductType]
      ,[GoogleProductCategory]
      ,[Brand]
      ,[Gender]
      ,[AgeGroup]
      ,[Color]
      ,[Size]
      ,[Material]
      ,[Pattern]
      ,[SizeType]
      ,[SizeSystem]
      ,[GoogleCategoryMatchID]
      ,[EnergyEfficiencyClass]
      ,[Adult]
      ,[IsBundle]
      ,[Multipack]
      ,[ShortTitle]
      ,[ProductDimensionsUnit]
      ,[ProductHeight]
      ,[ProductLength]
      ,[ProductWeight]
      ,[ProductWeightUnit]
      ,[ProductWidth]
  FROM [lighthousefeed_prod].[dbo].[Products]